### ISSUE TITLE
"Running Rspec..." message blank

### ISSUE THREAD

**Issue by bjacobson26** [mogulla3/rspec.nvim#5]
Hi there. This plugin is awesome, thank you for making it. 

I ran across an issue today after updating to neovim v0.10.2 where the "Running RSpec..." message was missing when the little box renders on the bottom right side of the screen. I fixed it by modifying a few things:

1. Use `vim.api.nvim_buf_set_lines(bufnr, 0, -1, true, { message })` to ensure the message gets added to the buffer.
2. Ensure the buffer is modifiable: Use `vim.api.nvim_buf_set_option(bufnr, 'modifiable', true)`
3. Use buffer option bufhidden as 'wipe': Cleans up the buffer when the window is closed

Not sure if this is the best solution, but it fixed the blank text. 

```lua
local function create_progress_window()
  local message = "Running RSpec..."
  local bufnr = vim.api.nvim_create_buf(false, true)

  -- Set buffer options to ensure the text can be added and displayed
  vim.api.nvim_buf_set_option(bufnr, 'modifiable', true)
  vim.api.nvim_buf_set_option(bufnr, 'bufhidden', 'wipe')

  -- Render floating window on the right bottom
  local opts = {
    relative = "win",
    anchor = "SE",
    focusable = false,
    row = vim.fn.winheight(0) - 2,
    col = vim.fn.winwidth(0) - 4,
    width = string.len(message),
    height = 1,
    style = "minimal",
    border = "rounded",
  }

  local win_id = vim.api.nvim_open_win(bufnr, false, opts)

  -- Set the content of the buffer
  vim.api.nvim_buf_set_lines(bufnr, 0, -1, true, { message })

  -- Set window highlight (optional)
  vim.api.nvim_set_option_value("winhl", "Normal:ErrorFloat", { win = win_id })

  return { win_id = win_id, bufnr = bufnr }
end


---@param progress_window { win_id: number, bufnr: number }
local function cleanup_progress_window(progress_window)
  -- Check if the window is valid before closing it
  if vim.api.nvim_win_is_valid(progress_window.win_id) then
    vim.api.nvim_win_close(progress_window.win_id, true)
  else
    print("Window " .. progress_window.win_id .. " is invalid and cannot be closed.")
  end

  -- Check if the buffer is valid before deleting it
  if vim.api.nvim_buf_is_valid(progress_window.bufnr) then
    vim.api.nvim_buf_delete(progress_window.bufnr, { force = true })
  else
    print("Buffer " .. progress_window.bufnr .. " is invalid and cannot be deleted.")
  end
end
```

**Comment by h3pei** [comment]
@bjacobson26 

Thank you for your feedback.

As you pointed out, the "Running RSpec..." message was not appearing in my environment either.

I have created a Pull Request based on the patch you provided as a reference.
https://github.com/mogulla3/rspec.nvim/pull/6

In my environment, the issue seems to be fixed with this PR, but there may still be some oversights.
I would appreciate it if you could provide further feedback if you notice anything else.
Thank you again!
